services:
  nginx:
    networks:
      - inception-nw
    build:
      context: requirements/nginx
      dockerfile: "Dockerfile"
    ports:
      - "8080:80"
    volumes:
      - web:/var/www/html
    depends_on:
      - wordpress
    restart: unless-stopped
  wordpress:
    networks:
      - inception-nw
    volumes:
      - web:/var/www/html
    build:
      context: requirements/wordpress
      dockerfile: "Dockerfile"
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_SITE_URL: ${WORDPRESS_SITE_URL}
      WORDPRESS_SITE_TITLE: ${WORDPRESS_SITE_TITLE}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
    restart: unless-stopped
  mariadb:
    networks:
      - inception-nw
    volumes:
      - db:/home/okoca/data/db
    build:
      context: requirements/mariadb
      dockerfile: "Dockerfile"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: unless-stopped

volumes:
  web:
    driver_opts:
      type: none
      device: /home/okoca/data/web
      o: bind
  db:
    driver_opts:
      type: none
      device: /home/okoca/data/db
      o: bind
networks:
  inception-nw:
    driver: bridge