services:
  nginx:
    networks:
      - inception-nw
    build:
      context: requirements/nginx
      dockerfile: "Dockerfile"
    ports:
      - "8080:80"
    volumes:
      - web:/home/okoca/data/web
  wordpress:
    networks:
      - inception-nw
    volumes:
      - web:/home/okoca/data/web
    build:
      context: requirements/wordpress
      dockerfile: "Dockerfile"
  mariadb:
    networks:
      - inception-nw
    volumes:
      - db:/home/okoca/data/db
    build:
      context: requirements/mariadb
      dockerfile: "Dockerfile"

volumes:
  web:
  db:

networks:
  inception-nw:
    driver: bridge