services:
  nginx:
    networks:
      - inception-nw
    build:
      context: requirements/nginx
      dockerfile: "Dockerfile"
    image: nginx
    pull_policy: never
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web:/var/www/html
    depends_on:
      - wordpress
      - static
      - adminer
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    restart: unless-stopped

  wordpress:
    networks:
      - inception-nw
    volumes:
      - web:/var/www/html
    build:
      context: requirements/wordpress
      dockerfile: "Dockerfile"
    image: wordpress
    pull_policy: never
    depends_on:
      - mariadb
      - redis
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_SITE_URL: ${DOMAIN_NAME}
      WORDPRESS_SITE_TITLE: ${WORDPRESS_SITE_TITLE}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      USER_USERNAME: ${USER_USERNAME}
      USER_EMAIL: ${USER_EMAIL}
      USER_PASSWORD: ${USER_PASSWORD}
    restart: unless-stopped

  mariadb:
    networks:
      - inception-nw
    volumes:
      - db:/var/lib/mysql
    build:
      context: requirements/mariadb
      dockerfile: "Dockerfile"
    image: mariadb
    pull_policy: never
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: unless-stopped

  redis:
    networks:
      - inception-nw
    build:
      context: requirements/redis
      dockerfile: "Dockerfile"
    image: redis
    pull_policy: never
    restart: unless-stopped

  ftp:
    networks:
      - inception-nw
    build:
      context: requirements/ftp
      dockerfile: "Dockerfile"
      args:
        FTP_USER: ${FTP_USER}
        FTP_PASSWORD: ${FTP_PASSWORD}
    image: ftp
    pull_policy: never
    volumes:
      - web:/web_data
    depends_on:
      - wordpress
    ports:
      - "20-21:20-21"
      - "30000-31000:30000-31000"
    restart: unless-stopped

  static:
    networks:
      - inception-nw
    build:
      context: requirements/static
      dockerfile: "Dockerfile"
    image: static
    pull_policy: never
    volumes:
      - web:/var/www/html
    restart: unless-stopped

  adminer:
    networks:
      - inception-nw
    build:
      context: requirements/adminer
      dockerfile: "Dockerfile"
    image: adminer
    depends_on:
      - mariadb
    pull_policy: never
    volumes:
      - web:/var/www/html
    restart: unless-stopped

  grafana:
    networks:
      - inception-nw
    build:
      context: requirements/grafana
      dockerfile: "Dockerfile"
    image: grafana
    # depends_on:
    #   - mariadb
    environment:
      GRAFANA_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GRAFANA_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    pull_policy: never
    restart: unless-stopped

volumes:
  web:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/web
      o: bind
  db:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/db
      o: bind
networks:
  inception-nw:
    driver: bridge