services:
  nginx:
    networks:
      - inception-nw
    build:
      context: requirements/nginx
      dockerfile: "Dockerfile"
    ports:
      - "8080:80"
    volumes:
      - web:/home/okoca/data/web
    depends_on:
      - wordpress
    restart: unless-stopped
  wordpress:
    networks:
      - inception-nw
    volumes:
      - web:/home/okoca/data/web
    build:
      context: requirements/wordpress
      dockerfile: "Dockerfile"
    depends_on:
      - mariadb
    restart: unless-stopped
  mariadb:
    networks:
      - inception-nw
    volumes:
      - db:/home/okoca/data/db
    build:
      context: requirements/mariadb
      dockerfile: "Dockerfile"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: unless-stopped

volumes:
  web:
  db:

networks:
  inception-nw:
    driver: bridge